name: kbengine
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.9.24=haa95532_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - cpython=3.13.0=py313hd8ed1ab_100
  - debugpy=1.8.7=py313h5813708_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - et_xmlfile=1.0.1=py_1001
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.6.3=h5da7b33_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.27.0=pyh7428d3b_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh5737063_1
  - krb5=1.21.3=hdf4eb48_0
  - libblas=3.9.0=1_h8933c1f_netlib
  - libcblas=3.9.0=5_hd5c7e75_netlib
  - libexpat=2.6.3=he0c23c2_0
  - libffi=3.4.4=hd77b12b_1
  - liblapack=3.9.0=5_hd5c7e75_netlib
  - libmpdec=4.0.0=h827c3e9_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.46.1=h2466b09_0
  - libzlib=1.3.1=h2466b09_2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2023.1.0=h6b88ed4_46358
  - msys2-conda-epoch=20160418=1
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - numpy=2.1.2=py313hd65a2fa_0
  - openpyxl=3.1.5=py313he57e174_1
  - openssl=3.3.2=h2466b09_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.3=py313hf91d08e_1
  - parso=0.8.4=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.2=pyh145f28c_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=6.0.0=py313ha7868ed_2
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.13.0=hf5aa216_100_cp313
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.13=0_cp313
  - pytz=2021.3=pyhd3eb1b0_0
  - pywin32=307=py313h5813708_3
  - pyzmq=26.2.0=py313h2100fd5_3
  - scikit-learn=1.5.2=py313h4f67946_1
  - scipy=1.14.1=py313hdf33807_0
  - setuptools=75.1.0=pyhd8ed1ab_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.4=py313h8e081ca_0
  - tbb=2021.8.0=h59b6b97_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=h5226925_1
  - tornado=6.4.1=py313ha7868ed_1
  - tqdm=4.66.5=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h04d1e81_0
  - ucrt=10.0.20348.0=haa95532_0
  - vc=14.40=h2eaa2aa_1
  - vc14_runtime=14.40.33810=hcc2c482_22
  - vs2015_runtime=14.40.33810=h3bf8584_22
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - xz=5.4.6=h8cc25b3_1
  - zeromq=4.3.5=ha9f60a1_6
  - zipp=3.20.2=pyhd8ed1ab_0
prefix: C:\Users\WH947CH\AppData\Local\anaconda3\envs\kbengine
